# This is a basic workflow to help you get started with Actions

name: screenshot-website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Screenshot Website
        id: screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://github.com/maxontech/maxontech
          destination: screenshot.png
          full-page: true
          
      - name: Get screenshot path
        run: echo "Screenshot path is ${{ steps.screenshot.outputs.path }}"

      - run: mv screenshot.png ${{ github.workspace }}

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Save screenshots
        uses: EndBug/add-and-commit@v4
        with:
          message: "Save screenshots"
          add: "*.png"
          




