name: Website Screenshots

on:
  push:
    branches:
      - main

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Take screenshots
        run: node .github/workflows/scripts/take-screenshots.js

      - name: Commit and push screenshots
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add screenshots
          git commit -m "Add screenshots"
          git push